In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import re
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [2]:
df = pd.read_csv('movie_list.csv')

In [3]:
df.head()

,Movie Name,Director,Release Date,Running Time,Country,Language,IMDB Rating,Genre,Number of votes
0,The Shawshank Redemption,Frank Darabont,14 October 1994 (USA),2h 22min,USA,English,9.3,Drama,"2,160,945"
1,The Godfather,Francis Ford Coppola,24 March 1972 (USA),2h 55min,USA,English,9.2,Crime,"1,483,111"
2,The Godfather: Part II,Francis Ford Coppola,20 December 1974 (USA),3h 22min,USA,English,9.0,Crime,"1,032,741"
3,The Dark Knight,Christopher Nolan,18 July 2008 (USA),2h 32min,USA,English,9.0,Action,"2,135,831"
4,12 Angry Men,Sidney Lumet,10 April 1957 (USA),1h 36min,USA,English,8.9,Drama,"618,051"

In [4]:
# indexing the dataframe
df.index = list(range(1,251))

The release date has country listed taht needs to be removed.

In [5]:
df['Country'].unique()

array(['USA', 'New Zealand', 'Italian', 'English', 'Japanese', 'Brazil',
       'Italy', 'Japan', 'South Korea', 'UK', 'France', 'Germany',
       'West Germany', 'Hindi', 'India', 'German', 'Denmark', 'Iran',
       'Lebanon', 'Canada', 'Mexico', 'Belarusian', 'Argentina', 'Turkey',
       'Swedish', 'Malayalam', 'Ireland', 'Turkish', 'Russian',
       'Australia', 'French', 'Hong Kong'], dtype=object)

In [6]:
#removing the country name from the Release Date column
df['Release Date'] = df['Release Date'].apply(lambda x: x.split('(')[0] )

In [7]:
# Add Release year(extracting only the year from the date column) and drop release date
yearregex = re.compile('\d\d\d\d')
def func(x):
    result = yearregex.search(x)
    return(result.group())
df['Release Year'] = df['Release Date'].apply(func)
df.drop(['Release Date'], axis=1, inplace=True)

In [8]:
df.head(10)

,Movie Name,Director,Running Time,Country,Language,IMDB Rating,Genre,Number of votes,Release Year
1,The Shawshank Redemption,Frank Darabont,2h 22min,USA,English,9.3,Drama,"2,160,945",1994
2,The Godfather,Francis Ford Coppola,2h 55min,USA,English,9.2,Crime,"1,483,111",1972
3,The Godfather: Part II,Francis Ford Coppola,3h 22min,USA,English,9.0,Crime,"1,032,741",1974
4,The Dark Knight,Christopher Nolan,2h 32min,USA,English,9.0,Action,"2,135,831",2008
5,12 Angry Men,Sidney Lumet,1h 36min,USA,English,8.9,Drama,"618,051",1957
6,Schindler's List,Steven Spielberg,3h 15min,USA,English,8.9,Biography,"1,120,938",1994
7,The Lord of the Rings: The Return of the King,Peter Jackson,3h 21min,New Zealand,English,8.9,Adventure,"1,534,424",2003
8,Pulp Fiction,Quentin Tarantino,2h 34min,USA,English,8.9,Crime,"1,696,169",1994
9,"The Good, the Bad and the Ugly",Sergio Leone,2h 58min,Italian,See more,8.8,Western,"641,284",1967
10,Fight Club,David Fincher,2h 19min,USA,English,8.8,Drama,"1,726,399",1999

'See More' is not a language in the language column. The language is present in the country column.

In [9]:
langmiss = df.loc[df['Language']=='See more'].index

In [10]:
langmiss

Int64Index([  9,  18,  20,  25,  30,  33,  40,  41,  44,  47,  48,  50,  51,
             58,  63,  66,  68,  70,  72,  79,  87,  89,  91,  95,  96,  97,
             99, 101, 102, 103, 104, 107, 109, 110, 115, 120, 122, 125, 130,
            132, 134, 138, 139, 141, 144, 145, 148, 149, 150, 154, 155, 160,
            161, 162, 163, 165, 169, 172, 175, 177, 178, 180, 181, 185, 188,
            189, 191, 194, 195, 198, 200, 202, 203, 207, 208, 210, 213, 214,
            216, 218, 223, 224, 225, 226, 229, 239, 243, 248, 249],
           dtype='int64')

In [11]:
for i in langmiss:
    df.ix[i,4] = df.ix[i,3]

In [12]:
df.Country.unique()

array(['USA', 'New Zealand', 'Italian', 'English', 'Japanese', 'Brazil',
       'Italy', 'Japan', 'South Korea', 'UK', 'France', 'Germany',
       'West Germany', 'Hindi', 'India', 'German', 'Denmark', 'Iran',
       'Lebanon', 'Canada', 'Mexico', 'Belarusian', 'Argentina', 'Turkey',
       'Swedish', 'Malayalam', 'Ireland', 'Turkish', 'Russian',
       'Australia', 'French', 'Hong Kong'], dtype=object)

In [13]:
langcorr = {'Japanese':'Japan','Italian':'Italy','English':'USA','Hindi':'India','German':'Germany',
           'French':'France', 'Swedish':'Sweden', 'Belarusian':'Soviet Union', 'Russian':'Russia', 
           'Turkish':'Turkey', 'Korean':'South Korea'}

In [14]:
for i in range(1,251):
    if df['Country'].ix[i] in langcorr.keys():
        df['Country'].ix[i] = langcorr[df['Country'].ix[i]]

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [15]:
df.head(10)

,Movie Name,Director,Running Time,Country,Language,IMDB Rating,Genre,Number of votes,Release Year
1,The Shawshank Redemption,Frank Darabont,2h 22min,USA,English,9.3,Drama,"2,160,945",1994
2,The Godfather,Francis Ford Coppola,2h 55min,USA,English,9.2,Crime,"1,483,111",1972
3,The Godfather: Part II,Francis Ford Coppola,3h 22min,USA,English,9.0,Crime,"1,032,741",1974
4,The Dark Knight,Christopher Nolan,2h 32min,USA,English,9.0,Action,"2,135,831",2008
5,12 Angry Men,Sidney Lumet,1h 36min,USA,English,8.9,Drama,"618,051",1957
6,Schindler's List,Steven Spielberg,3h 15min,USA,English,8.9,Biography,"1,120,938",1994
7,The Lord of the Rings: The Return of the King,Peter Jackson,3h 21min,New Zealand,English,8.9,Adventure,"1,534,424",2003
8,Pulp Fiction,Quentin Tarantino,2h 34min,USA,English,8.9,Crime,"1,696,169",1994
9,"The Good, the Bad and the Ugly",Sergio Leone,2h 58min,Italy,Italian,8.8,Western,"641,284",1967
10,Fight Club,David Fincher,2h 19min,USA,English,8.8,Drama,"1,726,399",1999

The IMDB rating is a float value and not a string value. It needs to be converted

In [16]:
df['IMDB Rating'] = df['IMDB Rating'].apply(lambda x: float(x))

The runtime data comprises of hours and minutes. Converting it to only minutes.

In [17]:
def func(x):
    a = int(x.split('h')[0])*60 
    b = x.split('h')[1].split('min')[0].strip()
    if b=='':
        b=0
    else:
        b = int(x.split('h')[1].split('min')[0].strip())
    return(a+b)
df['Running Time'] = df['Running Time'].apply(func)

In [18]:
df.head(10)

,Movie Name,Director,Running Time,Country,Language,IMDB Rating,Genre,Number of votes,Release Year
1,The Shawshank Redemption,Frank Darabont,142,USA,English,9.3,Drama,"2,160,945",1994
2,The Godfather,Francis Ford Coppola,175,USA,English,9.2,Crime,"1,483,111",1972
3,The Godfather: Part II,Francis Ford Coppola,202,USA,English,9.0,Crime,"1,032,741",1974
4,The Dark Knight,Christopher Nolan,152,USA,English,9.0,Action,"2,135,831",2008
5,12 Angry Men,Sidney Lumet,96,USA,English,8.9,Drama,"618,051",1957
6,Schindler's List,Steven Spielberg,195,USA,English,8.9,Biography,"1,120,938",1994
7,The Lord of the Rings: The Return of the King,Peter Jackson,201,New Zealand,English,8.9,Adventure,"1,534,424",2003
8,Pulp Fiction,Quentin Tarantino,154,USA,English,8.9,Crime,"1,696,169",1994
9,"The Good, the Bad and the Ugly",Sergio Leone,178,Italy,Italian,8.8,Western,"641,284",1967
10,Fight Club,David Fincher,139,USA,English,8.8,Drama,"1,726,399",1999

In [19]:
df.to_csv('IMDBcleaned.csv', index=False)